Nota de Reprodutibilidade: Os arquivos originais XWines_Full_100K_wines.csv e XWines_Full_21M_ratings.csv excedem o limite de tamanho do GitHub. Para reproduzir este notebook do zero, faça o download da base X-Wines [(https://github.com/b18x/wine_ml)] e insira os arquivos na mesma pasta deste script."

In [1]:
import pandas as pd

# 1. INGESTÃO DOS DADOS
print("Iniciando a leitura dos arquivos...")
df_wines = pd.read_csv('XWines_Full_100K_wines.csv')
df_ratings = pd.read_csv('XWines_Full_21M_ratings.csv')

print("Unindo as tabelas (Merge)...")
df_completo = pd.merge(df_ratings, df_wines, on='WineID', how='inner')

print(f"Ingestão concluída! O dataset possui {df_completo.shape[0]} linhas e {df_completo.shape[1]} colunas.")
display(df_completo.head())

Iniciando a leitura dos arquivos...

C:\Users\aruba\AppData\Local\Temp\ipykernel_13784\654527946.py:6: DtypeWarning: Columns (3: Vintage) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ratings = pd.read_csv('XWines_Full_21M_ratings.csv')

Unindo as tabelas (Merge)...
Ingestão concluída! O dataset possui 21013536 linhas e 22 colunas.

,RatingID,UserID,WineID,Vintage,Rating,Date,WineName,Type,Elaborate,Grapes,...,Body,Acidity,Code,Country,RegionID,RegionName,WineryID,WineryName,Website,Vintages
0,1,1604441,136103,1950,4.0,2019-10-14 11:20:52,Lambrusco Emilia,Red,Varietal/100%,['Lambrusco'],...,Full-bodied,High,IT,Italy,1581,Emilia,42951,Riunite,http://www.riunite.com,"[2021, 2020, 2019, 2018, 2017, 2016, 2015, 201..."
1,2,1291483,136103,1950,5.0,2019-11-28 03:36:33,Lambrusco Emilia,Red,Varietal/100%,['Lambrusco'],...,Full-bodied,High,IT,Italy,1581,Emilia,42951,Riunite,http://www.riunite.com,"[2021, 2020, 2019, 2018, 2017, 2016, 2015, 201..."
2,3,1070605,104036,1950,5.0,2017-12-28 10:15:55,Terrantez Madeira,Dessert/Port,Varietal/100%,['Terrantez'],...,Very full-bodied,High,PT,Portugal,1056,Madeira,12993,D'Oliveiras,NaN,"[2021, 2017, 2016, 2015, 2014, 2013, 2012, 201..."
3,4,1080181,144864,1950,5.0,2016-06-23 02:16:22,Lambrusco Emilia Rosé,Rosé,Varietal/100%,['Lambrusco'],...,Full-bodied,Low,IT,Italy,1581,Emilia,42951,Riunite,http://www.riunite.com,"[2021, 2020, 2019, 2018, 2017, 2016, 2015, 201..."
4,5,1834379,111430,1950,5.0,2021-05-16 17:58:14,Pomerol,Red,Varietal/100%,['Merlot'],...,Full-bodied,Medium,FR,France,1404,Pomerol,30059,Pétrus,http://www.moueix.com,"[2021, 2020, 2019, 2018, 2017, 2016, 2015, 201..."

In [2]:
# 2. AVALIAÇÃO DA QUALIDADE
print("--- INFORMAÇÕES GERAIS E TIPOS DE DADOS ---")
display(df_completo.info())

print("\n--- VALORES AUSENTES (NULOS) ---")
valores_nulos = df_completo.isnull().sum()
display(valores_nulos[valores_nulos > 0])

print("\n--- ESTATÍSTICAS DESCRITIVAS (Identificando Outliers no ABV) ---")
display(df_completo.describe())

--- INFORMAÇÕES GERAIS E TIPOS DE DADOS ---
<class 'pandas.DataFrame'>
RangeIndex: 21013536 entries, 0 to 21013535
Data columns (total 22 columns):
 #   Column      Dtype
---  ------      -----
 0   RatingID    int64
 1   UserID      int64
 2   WineID      int64
 3   Vintage     object
 4   Rating      float64
 5   Date        str
 6   WineName    str
 7   Type        str
 8   Elaborate   str
 9   Grapes      str
 10  Harmonize   str
 11  ABV         float64
 12  Body        str
 13  Acidity     str
 14  Code        str
 15  Country     str
 16  RegionID    int64
 17  RegionName  str
 18  WineryID    int64
 19  WineryName  str
 20  Website     str
 21  Vintages    str
dtypes: float64(2), int64(5), object(1), str(14)
memory usage: 3.4+ GB

None

--- VALORES AUSENTES (NULOS) ---

Website    2440869
dtype: int64

--- ESTATÍSTICAS DESCRITIVAS (Identificando Outliers no ABV) ---

,RatingID,UserID,WineID,Rating,ABV,RegionID,WineryID
count,2.101354e+07,2.101354e+07,2.101354e+07,2.101354e+07,2.101354e+07,2.101354e+07,2.101354e+07
mean,1.050677e+07,1.433101e+06,1.472873e+05,3.884880e+00,1.351755e+01,1.762362e+03,4.205552e+04
std,6.066085e+06,3.087566e+05,2.765525e+04,7.375787e-01,1.208528e+00,4.489517e+02,1.699914e+04
min,1.000000e+00,1.000001e+06,1.000010e+05,1.000000e+00,0.000000e+00,1.000000e+03,1.000000e+04
25%,5.253385e+06,1.180506e+06,1.181590e+05,3.500000e+00,1.300000e+01,1.423000e+03,2.989900e+04
50%,1.050677e+07,1.357576e+06,1.553130e+05,4.000000e+00,1.350000e+01,1.763000e+03,4.141800e+04
75%,1.576015e+07,1.692543e+06,1.688950e+05,4.500000e+00,1.400000e+01,2.058000e+03,5.645200e+04
max,2.101354e+07,2.063390e+06,2.007950e+05,5.000000e+00,5.000000e+01,3.750000e+03,7.184000e+04

In [5]:
# 3. LIMPEZA E PREPARAÇÃO DOS DADOS
print("Iniciando a limpeza dos dados...")
df_clean = df_completo.copy()

# A. Removendo colunas desnecessárias
# Justificativa: A coluna 'Website' possui muitos valores nulos e não agrega valor à análise estatística.
if 'Website' in df_clean.columns:
    df_clean = df_clean.drop(columns=['Website'])
    print("- Coluna 'Website' removida.")

# B. Tratamento de Outliers (Valores Inválidos)
# Justificativa: Filtrar Teor Alcoólico (ABV) para manter apenas bebidas reais (entre 4% e 25%).
qtd_antes = df_clean.shape[0]
df_clean = df_clean[(df_clean['ABV'] > 4.0) & (df_clean['ABV'] <= 25.0)]
qtd_depois = df_clean.shape[0]
print(f"- Removidos {qtd_antes - qtd_depois} registros com Teor Alcoólico (ABV) inválido ou extremo.")

# C. Correção de Tipos de Dados
# Justificativa: IDs e Safras são números inteiros, e a coluna Date precisa do formato datetime para análises futuras.
print("Corrigindo tipos de dados (aguarde, processando datas...)")
df_clean['WineID'] = df_clean['WineID'].astype(int)
df_clean['Vintage'] = pd.to_numeric(df_clean['Vintage'], errors='coerce')
df_clean['Vintage'] = df_clean['Vintage'].astype('Int64')
df_clean['Date'] = pd.to_datetime(df_clean['Date'], format='mixed')

print("\nLimpeza concluída com sucesso!")

Iniciando a limpeza dos dados...
- Coluna 'Website' removida.
- Removidos 3013 registros com Teor Alcoólico (ABV) inválido ou extremo.
Corrigindo tipos de dados (aguarde, processando datas...)

Limpeza concluída com sucesso!

In [6]:
# 4. EXPORTAÇÃO DO CONJUNTO DE DADOS RESULTANTE
print("Gerando o arquivo final limpo...")

# Extraindo 100 mil linhas aleatórias para evitar estourar o limite de 100MB do GitHub
df_amostra = df_clean.sample(n=100000, random_state=42)
df_amostra.to_csv('x_wines_preparado_amostra.csv', index=False)

print("\n--- INFORMAÇÕES DO DATASET PREPARADO ---")
display(df_amostra.info())

print("\nArquivo 'x_wines_preparado_amostra.csv' gerado e pronto para a entrega!")
display(df_amostra.head())

Gerando o arquivo final limpo...

--- INFORMAÇÕES DO DATASET PREPARADO ---
<class 'pandas.DataFrame'>
Index: 100000 entries, 19387101 to 7339578
Data columns (total 21 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   RatingID    100000 non-null  int64
 1   UserID      100000 non-null  int64
 2   WineID      100000 non-null  int64
 3   Vintage     97961 non-null   Int64
 4   Rating      100000 non-null  float64
 5   Date        100000 non-null  datetime64[us]
 6   WineName    100000 non-null  str
 7   Type        100000 non-null  str
 8   Elaborate   100000 non-null  str
 9   Grapes      100000 non-null  str
 10  Harmonize   100000 non-null  str
 11  ABV         100000 non-null  float64
 12  Body        100000 non-null  str
 13  Acidity     100000 non-null  str
 14  Code        100000 non-null  str
 15  Country     100000 non-null  str
 16  RegionID    100000 non-null  int64
 17  RegionName  100000 non-null  str
 18  WineryID    100000 non-null  int64
 19  WineryName  100000 non-null  str
 20  Vintages    100000 non-null  str
dtypes: Int64(1), datetime64[us](1), float64(2), int64(5), str(12)
memory usage: 16.9 MB

None

Arquivo 'x_wines_preparado_amostra.csv' gerado e pronto para a entrega!

,RatingID,UserID,WineID,Vintage,Rating,Date,WineName,Type,Elaborate,Grapes,...,ABV,Body,Acidity,Code,Country,RegionID,RegionName,WineryID,WineryName,Vintages
19387101,19387102,1986635,168004,2019,5.0,2020-08-02 01:44:09,Cabernet-Malbec,Red,Assemblage/Bordeaux Red Blend,"['Cabernet Sauvignon', 'Malbec']",...,13.5,Full-bodied,High,AR,Argentina,2058,Mendoza,61700,Estancia Mendoza,"[2021, 2020, 2019, 2018, 2017, 2016, 2015, 201..."
7019272,7019273,1106820,179511,2013,4.0,2017-09-02 17:53:50,Napa Valley Cabernet Sauvignon,Red,Varietal/100%,['Cabernet Sauvignon'],...,14.4,Full-bodied,Medium,US,United States,1848,Napa Valley,56467,Emblem,"[2021, 2020, 2019, 2018, 2017, 2016, 2015, 201..."
16771071,16771072,1162201,193793,2018,3.5,2019-08-19 11:58:27,Rosé de Purcari,Rosé,Assemblage/Blend,"['Cabernet Sauvignon', 'Merlot']",...,13.5,Full-bodied,Medium,MD,Moldova,2450,South Eastern,68538,Château Purcari,"[2021, 2020, 2019, 2018, 2017, 2016, 2015, 201..."
14112349,14112350,1048414,158877,2016,4.0,2017-01-15 22:38:42,Albariño,White,Varietal/100%,['Albariño'],...,13.0,Medium-bodied,High,ES,Spain,2018,Rías Baixas,38287,Heredad Chavarri,"[2021, 2020, 2019, 2018, 2016, 2015, 2014, 201..."
15998027,15998028,1182531,106710,2017,3.0,2020-07-31 06:21:05,Spätburgunder (Markgräflerland),Red,Varietal/100%,['Spätburgunder'],...,13.5,Full-bodied,High,DE,Germany,1080,Baden,13293,Martin Waßmer,"[2021, 2020, 2019, 2018, 2017, 2016, 2015, 201..."